spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: youssef
    password: password12345
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
#      ddl-auto: none
#      ddl-auto: drop
#      ddl-auto: create
  application:
    name: SMS
